from __future__ import annotations

from dataclasses import dataclass


@dataclass
class ClauseRule:
    key: str  # machine key, e.g. "rent_escalation"
    label: str  # human-readable, e.g. "Rent Escalation Clause"
    keywords: list[str]  # lowercase substrings — if ANY appear in the document text, this clause topic is considered "present" / discussed
    red_flag_keywords: list[str]  # lowercase substrings — if ANY of THESE appear (checked only when the clause topic is present), it's a red flag
    safe_description: str  # one sentence: what a fair/reasonable version of this clause looks like
    red_flag_description: str  # one sentence: what the red-flag version looks like and why it's bad for the tenant/contractor
    severity: str  # "high" | "medium" | "low" — how bad a red-flag hit on this clause is


LEASE_CLAUSES: list[ClauseRule] = [
    ClauseRule(
        key="rent_escalation",
        label="Rent Escalation Clause",
        keywords=[
            "rent increase",
            "rent escalation",
            "increase in rent",
            "adjusted rent",
            "new rent amount",
            "annual increase",
            "rent adjustment",
            "upon renewal the rent",
        ],
        red_flag_keywords=[
            "at landlord's sole discretion",
            "at the landlord's sole discretion",
            "sole discretion of landlord",
            "landlord may increase rent",
            "no cap",
            "uncapped",
            "without limitation",
            "any amount landlord deems",
            "market rate at the time",
            "without prior notice",
            "no notice required",
            "effective immediately upon",
            "such increase as landlord",
        ],
        safe_description="A fair escalation clause caps any increase to a fixed percentage or CPI and requires at least 30-60 days written notice before it takes effect.",
        red_flag_description="This clause lets the landlord raise rent by any amount at their sole discretion with no notice period, exposing the tenant to unpredictable and unaffordable increases at any time.",
        severity="high",
    ),
    ClauseRule(
        key="security_deposit",
        label="Security Deposit Clause",
        keywords=[
            "security deposit",
            "damage deposit",
            "deposit",
            "refundable",
            "non-refundable",
            "return of deposit",
        ],
        red_flag_keywords=[
            "non-refundable",
            "nonrefundable",
            "shall not be refunded",
            "forfeited",
            "at landlord's discretion",
            "within a reasonable time",
            "no specific time",
            "deposit in the amount of three months",
            "deposit equal to three months",
            "deposit equal to two months' rent",
            "last two months' rent plus",
            "landlord may apply the deposit to",
            "retained in full",
        ],
        safe_description="A fair deposit is one to two months' rent, refundable minus documented damages, returned within a state-mandated window such as 14-30 days after move-out with an itemized statement.",
        red_flag_description="This clause allows an above-normal or non-refundable deposit and gives the landlord discretion over its return with no fixed timeline, effectively letting them keep the tenant's money without accountability.",
        severity="high",
    ),
    ClauseRule(
        key="renewal_autorenew",
        label="Renewal / Auto-Renewal Clause",
        keywords=[
            "renewal",
            "automatically renew",
            "auto-renew",
            "automatic renewal",
            "term shall renew",
            "extend the term",
            "notice of intent not to renew",
            "non-renewal",
        ],
        red_flag_keywords=[
            "automatically renew",
            "automatically be renewed",
            "shall be deemed renewed",
            "unless tenant provides written notice not less than",
            "failure to give notice of non-renewal",
            "penalty for failure to renew",
            "shall be liable for",
            "no right to opt out",
            "tenant waives the right to terminate",
            "administrative fee",
        ],
        safe_description="A fair renewal clause auto-renews only into a month-to-month or matching term and gives the tenant a clear window (e.g. 30-60 days) to opt out with no penalty.",
        red_flag_description="This clause auto-renews the tenant into a new full term unless they navigate a narrow opt-out window, and may charge a penalty or fee for not renewing, trapping the tenant in the lease.",
        severity="medium",
    ),
    ClauseRule(
        key="early_termination",
        label="Early Termination / Lease-Break Penalty Clause",
        keywords=[
            "early termination",
            "terminate early",
            "break the lease",
            "lease break",
            "abandon the premises",
            "liquidated damages",
            "reletting",
            "buyout",
        ],
        red_flag_keywords=[
            "responsible for all remaining rent",
            "entire remaining balance of rent",
            "rent for the full unexpired term",
            "two months' rent",
            "three months' rent as",
            "liquidated damages",
            "no obligation to mitigate",
            "shall not be required to mitigate",
            "landlord shall have no duty to relet",
            "plus all future rent",
            "acceleration clause",
            "immediately due and payable",
        ],
        safe_description="A fair clause sets a reasonable, pre-agreed fee (commonly one to two months' rent) and requires the landlord to make good-faith efforts to re-rent the unit to offset the tenant's liability.",
        red_flag_description="This clause makes the tenant liable for all rent through the end of the full term with no cap and explicitly excuses the landlord from mitigating damages by re-renting, maximizing the tenant's loss on a break.",
        severity="high",
    ),
    ClauseRule(
        key="maintenance_repairs",
        label="Maintenance / Repair Responsibility Clause",
        keywords=[
            "maintenance",
            "repair",
            "repairs",
            "condition of the premises",
            "habitability",
            "wear and tear",
            "upkeep",
        ],
        red_flag_keywords=[
            "tenant shall be responsible for all repairs",
            "tenant is responsible for repairs",
            "including structural",
            "roof, foundation",
            "plumbing and electrical systems",
            "heating and cooling systems",
            "hvac",
            "appliance repair",
            "pest control at tenant's expense",
            "at tenant's sole cost and expense",
            "tenant waives the right to",
            "as-is condition",
            "landlord shall have no obligation to repair",
            "no warranty of habitability",
        ],
        safe_description="A fair clause keeps the landlord responsible for structural, system, and habitability-related repairs, with the tenant only handling minor day-to-day upkeep and damage they cause.",
        red_flag_description="This clause shifts structural and major-system repair costs (roof, plumbing, HVAC, appliances) onto the tenant or disclaims the landlord's habitability obligations, forcing the tenant to pay for the landlord's legal duties.",
        severity="high",
    ),
    ClauseRule(
        key="entry_access",
        label="Landlord Entry / Access Rights Clause",
        keywords=[
            "right of entry",
            "enter the premises",
            "access to the premises",
            "entry",
            "inspect the premises",
            "show the premises",
            "prior notice",
        ],
        red_flag_keywords=[
            "at any time",
            "at any time for any reason",
            "without notice",
            "without prior notice",
            "no notice",
            "with or without notice",
            "as landlord deems necessary",
            "landlord retains keys",
            "landlord may enter",
            "tenant shall not deny entry",
            "waives any requirement of notice",
            "24 hours",
        ],
        safe_description="A fair entry clause requires reasonable advance written notice (typically 24-48 hours), limits entry to legitimate purposes like repairs or showings, and restricts it to reasonable hours except in emergencies.",
        red_flag_description="This clause permits the landlord to enter at any time for any reason without notice, eliminating the tenant's quiet enjoyment and privacy in their own home.",
        severity="medium",
    ),
    ClauseRule(
        key="subletting_guests",
        label="Subletting / Guest Restrictions Clause",
        keywords=[
            "sublet",
            "subletting",
            "sublease",
            "assign the lease",
            "guest",
            "guests",
            "occupant",
            "overnight guest",
        ],
        red_flag_keywords=[
            "shall not sublet",
            "no subletting",
            "under no circumstances",
            "absolute prohibition",
            "without exception",
            "no guests",
            "may not stay overnight",
            "no more than",
            "consecutive nights",
            "deemed an occupant",
            "additional rent for each guest",
            "per guest per night",
            "shall constitute a breach",
        ],
        safe_description="A fair clause allows subletting or assignment with landlord consent (not to be unreasonably withheld) and permits reasonable guest stays before a long-term guest must be added to the lease.",
        red_flag_description="This clause imposes a blanket ban on subletting with no consent path and sets unreasonably strict guest limits (e.g. counting brief stays as unauthorized occupants), exposing the tenant to breach claims over ordinary visits.",
        severity="medium",
    ),
]

CONTRACT_CLAUSES: list[ClauseRule] = [
    ClauseRule(
        key="liability",
        label="Liability Clause",
        keywords=[
            "liability",
            "liabilities",
            "damages",
            "liable",
            "consequential damages",
            "limitation of liability",
            "liability cap",
        ],
        red_flag_keywords=[
            "unlimited liability",
            "without limitation",
            "shall not be limited",
            "indemnify and hold harmless",
            "any and all damages",
            "all losses",
            "including but not limited to",
            "consequential, incidental, special",
            "indirect damages arising from",
            "in no event shall client's liability",
            "arising out of or related to this agreement and",
            "irrespective of cause",
        ],
        safe_description="A fair liability clause caps each party's total liability at a defined amount (commonly the fees paid under the contract) and mutually excludes indirect/consequential damages.",
        red_flag_description="This clause exposes the contractor to unlimited liability for any and all damages, including consequential ones the contractor cannot foresee or insure, with no cap tied to fees paid.",
        severity="high",
    ),
    ClauseRule(
        key="ip_assignment",
        label="Intellectual Property Assignment Clause",
        keywords=[
            "intellectual property",
            "assignment of rights",
            "assigns all right, title, and interest",
            "work product",
            "copyright",
            "ownership of deliverables",
            "license",
        ],
        red_flag_keywords=[
            "all right, title, and interest",
            "whether or not created under this agreement",
            "throughout the universe",
            "in perpetuity",
            "including all pre-existing",
            "background ip",
            "hereby irrevocably assigns",
            "conceived or reduced to practice",
            "during the term of this agreement or",
            "relating to the business of client",
            "waives all moral rights",
            "work made for hire",
            "at no additional compensation",
        ],
        safe_description="A fair IP clause assigns only the deliverables created and paid for under the contract, with the contractor keeping pre-existing tools and reusable background IP (licensed as needed).",
        red_flag_description="This clause assigns ALL of the contractor's IP — including pre-existing, unrelated, and even concurrently-created work — outright, permanently stripping the contractor of their toolkit and future work product for one project's fee.",
        severity="high",
    ),
    ClauseRule(
        key="termination",
        label="Termination Clause",
        keywords=[
            "termination",
            "terminate",
            "terminate this agreement",
            "notice of termination",
            "for convenience",
            "for cause",
            "kill fee",
        ],
        red_flag_keywords=[
            "at any time",
            "for any reason or no reason",
            "immediately upon written notice",
            "without cause",
            "upon written notice from client",
            "sole discretion of client",
            "contractor shall continue to perform",
            "shall remain in effect until",
            "non-cancellable",
            "minimum commitment",
            "no termination for convenience",
            "contractor may not terminate",
            "without penalty to client",
        ],
        safe_description="A fair termination clause is symmetric: either party can exit with reasonable written notice (e.g. 30 days), and the contractor is paid for all work performed up to termination, including a kill fee for projects cancelled mid-stream.",
        red_flag_description="This clause lets the client terminate immediately and for any reason with no kill fee or payment for in-flight work, while locking the contractor into the term with no exit right — all the risk sits on one side.",
        severity="high",
    ),
    ClauseRule(
        key="payment_terms",
        label="Payment Terms Clause",
        keywords=[
            "payment",
            "payment terms",
            "invoicing",
            "invoice",
            "net 30",
            "fees",
            "compensation",
            "late payment",
        ],
        red_flag_keywords=[
            "net 60",
            "net 75",
            "net 90",
            "net-60",
            "net-90",
            "payment within ninety days",
            "at client's discretion",
            "at the client's sole discretion",
            "upon client's satisfaction",
            "if and when client receives payment",
            "pay if paid",
            "no interest",
            "upon acceptance",
            "satisfactory completion as determined by client",
            "payment is discretionary",
        ],
        safe_description="A fair payment clause uses net-15 to net-30 terms from invoice, defines acceptance objectively with a deemed-acceptance backstop, and accrues interest on late payments.",
        red_flag_description="This clause stretches payment out to net-60/90 or longer, makes payment contingent on the client's subjective satisfaction or discretion (even a pay-if-paid contingency), and imposes no late-payment penalty, letting the client delay payment indefinitely.",
        severity="medium",
    ),
    ClauseRule(
        key="non_compete",
        label="Non-Compete / Non-Solicitation Clause",
        keywords=[
            "non-compete",
            "noncompete",
            "non-compete agreement",
            "non-solicitation",
            "restrictive covenant",
            "shall not compete",
            "shall not solicit",
        ],
        red_flag_keywords=[
            "anywhere in the world",
            "worldwide",
            "throughout the universe",
            "for a period of",
            "years following",
            "two (2) years",
            "three (3) years",
            "five (5) years",
            "any competitor",
            "any business similar to",
            "shall not directly or indirectly",
            "clients, customers, and prospects",
            "employees, contractors, and vendors",
            "during the term and thereafter",
            "in perpetuity",
        ],
        safe_description="A fair non-compete is narrowly scoped — e.g. direct solicitation of this client's known customers and staff for 6-12 months — and doesn't bar the contractor from their general field or industry.",
        red_flag_description="This clause bars the contractor from working for any similar business worldwide for multiple years, effectively making them unemployable in their own specialty after the contract ends.",
        severity="high",
    ),
    ClauseRule(
        key="indemnification",
        label="Indemnification Clause",
        keywords=[
            "indemnify",
            "indemnification",
            "hold harmless",
            "defend",
            "third-party claims",
            "claims",
        ],
        red_flag_keywords=[
            "shall indemnify, defend, and hold harmless",
            "any and all claims",
            "arising out of",
            "including claims arising from client's",
            "client's negligence",
            "negligence or misconduct of client",
            "regardless of cause",
            "one-way",
            "solely at contractor's expense",
            "contractor shall indemnify client against",
            "without limitation",
            "whether or not caused by",
        ],
        safe_description="A fair indemnification is mutual, limited to third-party claims arising from the indemnifying party's own negligent acts or material breach, and excludes the other side's independent wrongdoing.",
        red_flag_description="This clause makes the contractor indemnify the client even for claims arising from the client's own negligence or misuse, converting a one-way shield into open-ended financial exposure.",
        severity="high",
    ),
    ClauseRule(
        key="confidentiality",
        label="Confidentiality / NDA Scope Clause",
        keywords=[
            "confidential information",
            "confidentiality",
            "non-disclosure",
            "nondisclosure",
            "trade secrets",
            "disclose",
        ],
        red_flag_keywords=[
            "in perpetuity",
            "perpetual",
            "forever",
            "shall remain confidential indefinitely",
            "without limitation",
            "all information",
            "any information disclosed",
            "whether or not marked confidential",
            "no time limit",
            "regardless of whether",
            "contractor's own developments",
            "residuals",
            "without carve-out",
            "survive indefinitely",
        ],
        safe_description="A fair NDA defines confidential information specifically, lasts a reasonable period (2-5 years, longer only for trade secrets), and carves out information that is public, already known, independently developed, or rightfully received from third parties.",
        red_flag_description=(
            "This clause imposes perpetual, unlimited confidentiality over vaguely-defined "
            '"all information" with no carve-out for public or independently-developed '
            "knowledge, permanently restricting the contractor's ability to use their own expertise."
        ),
        severity="medium",
    ),
]
